ame: Check-URL

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: urls-checker
        uses: urlstechie/urlchecker-action@0.0.27
        with:
          subfolder: _data, _site
          file_types: .yml, .yaml, .html
          include_files: _layouts/base.html
          exclude_files: _site/README.md, _site/feed.xml
          print_all: false
          timeout: 5
          retry_count: 3
          force_pass : true